# Generated by Django 3.0.3 on 2020-05-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20200520_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerupload',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
