# Generated by Django 3.0.3 on 2020-05-17 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_uploadfarmer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfarmer',
            name='image',
        ),
    ]
