# Generated by Django 3.0.3 on 2020-05-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_auto_20200522_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerupload',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
