# Generated by Django 3.0.3 on 2020-05-31 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0007_auto_20200522_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer',
            old_name='Id',
            new_name='ID',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='CPass',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='Occupation',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='Pass',
        ),
        migrations.AlterField(
            model_name='farmer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
